# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adhar < Formula
  desc "Open Foundation for Cloud-Native Platform Engineering"
  homepage "https://adhar.io"
  version "0.1.14"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adhar-io/adhar/releases/download/v0.1.14/adhar-0.1.14-darwin-amd64.tar.gz"
      sha256 "2ac2b61ceac20aae3f45eac3edf5677db21ff98fcbfe846ecd840904e24c4fd5"

      def install
        bin.install "adhar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adhar-io/adhar/releases/download/v0.1.14/adhar-0.1.14-darwin-arm64.tar.gz"
      sha256 "1fb7e2a9d5c99c93931a3b88a018f0e07e33c4f9eb3e2e47af5f0f97313690f0"

      def install
        bin.install "adhar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adhar-io/adhar/releases/download/v0.1.14/adhar-0.1.14-linux-amd64.tar.gz"
        sha256 "3dc6fd69e09bcc2b25dad8a02a9c01637d17201168d54b629ac105d752e7a5f9"

        def install
          bin.install "adhar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adhar-io/adhar/releases/download/v0.1.14/adhar-0.1.14-linux-arm64.tar.gz"
        sha256 "11cf45ce75e33254c2f2b2be7c30c9888921b0174da8bdf9ee6dd9eaa807023c"

        def install
          bin.install "adhar"
        end
      end
    end
  end

  test do
    system "#{bin}/adhar version --short"
  end
end
