# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adhar < Formula
  desc "Open Foundation for Cloud-Native Platform Engineering"
  homepage "https://adhar.io"
  version "0.1.24"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adhar-io/adhar/releases/download/v0.1.24/adhar-0.1.24-darwin-amd64.tar.gz"
      sha256 "d7e9809cb8e96edce03991af6ff025ba467c397bd2f93efcd1a35ce91ca61476"

      def install
        bin.install "adhar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adhar-io/adhar/releases/download/v0.1.24/adhar-0.1.24-darwin-arm64.tar.gz"
      sha256 "4ddaad071d69b5c5783eafdbaf9a28d6c2d7f2e70f6bcdb22dd5dc803b6c098a"

      def install
        bin.install "adhar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adhar-io/adhar/releases/download/v0.1.24/adhar-0.1.24-linux-amd64.tar.gz"
        sha256 "b9e017edf1e9ba5a3a14f0c5c99c6d73fb6da008c0b947e28f59b259787c83a6"

        def install
          bin.install "adhar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adhar-io/adhar/releases/download/v0.1.24/adhar-0.1.24-linux-arm64.tar.gz"
        sha256 "c3d2404835041485b4cdd67c18b1e04e9b55ab215ef2d28c202b6f92e9ddde91"

        def install
          bin.install "adhar"
        end
      end
    end
  end

  test do
    system "#{bin}/adhar version --short"
  end
end
