# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Adhar < Formula
  desc "Open Foundation for Cloud-Native Platform Engineering"
  homepage "https://adhar.io"
  version "0.2.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/adhar-io/adhar/releases/download/v0.2.1/adhar-0.2.1-darwin-amd64.tar.gz"
      sha256 "10c5025a241c872969a95f550b0149be363e96630d4380a17945e1d46d57d5e2"

      def install
        bin.install "adhar"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/adhar-io/adhar/releases/download/v0.2.1/adhar-0.2.1-darwin-arm64.tar.gz"
      sha256 "b2eb2c3aab1bcf5453d3d7fb60f8809745734ff7f88a34386174c0f91f4c025f"

      def install
        bin.install "adhar"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adhar-io/adhar/releases/download/v0.2.1/adhar-0.2.1-linux-amd64.tar.gz"
        sha256 "bbf214b130e5e04e683751c8989e06c31b8d3da1574c810b8a78859cb5096e68"

        def install
          bin.install "adhar"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/adhar-io/adhar/releases/download/v0.2.1/adhar-0.2.1-linux-arm64.tar.gz"
        sha256 "88be1292e20a2c4006fcb903b1bfcd6f23ac9a0b19b0696f2aa49b3957c3f11b"

        def install
          bin.install "adhar"
        end
      end
    end
  end

  test do
    system "#{bin}/adhar version --short"
  end
end
